// Main Store
export const SET_USERS_REF = 'SET_USERS_REF'

// Duties Store
export const SET_DUTY_TEMPLATES_REF = 'SET_DUTY_TEMPLATES_REF'
export const SET_ALL_DUTIES_REF = 'SET_ALL_DUTIES_REF'
export const SET_WEEK_DUTIES_REF = 'SET_WEEK_DUTIES_REF'
export const SET_USER_DUTIES_REF = 'SET_USER_DUTIES_REF'

// Punts Store
export const SET_ALL_PUNTS_REF = 'SET_ALL_PUNTS_REF'
export const SET_USER_PUNTS_REF = 'SET_USER_PUNTS_REF'
export const SET_PUNT_MAKEUPS_REF = 'SET_PUNT_MAKEUPS_REF'
export const SET_PUNT_MAKEUP_TEMPLATES_REF = 'SET_PUNT_MAKEUP_TEMPLATES_REF'

// Social Store
export const SET_PARTIES_REF = 'SET_PARTIES_REF'
